gems:
  - jekyll
  - jekyll-sitemap

url: https://manmeetgill.com

exclude:
  - ".*"
  - "*.yml"
  - "CNAME"
  - "ci.Gemfile"
  - "Gemfile.lock"
  - "*.md"
  - "package.json"
  - "test.ps1"
  - "travis"
  - "node_modules**"
  - "yarn.lock"
  - "gulpfile.js"

include:
  - "_redirects"