gems:
  - jekyll
  - jekyll-redirect-from
  - jekyll-sitemap

webrick:
  headers:
    Cache-Control: max-age=14400

exclude:
  - ".*"
  - "*.yml"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "*.md"
  - "manifest.json"
  - "package.json"
  - "test.ps1"
  - "travis"
  - "tf2manu994.github.io.sublime-project"
  - "node_modules**"